FROM debian:stable-slim
RUN apt-get update && apt-get install -y --no-install-recommends \
    poppler-utils pandoc bash ca-certificates \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /work
ENTRYPOINT ["/bin/bash","-lc"]
