#!/usr/bin/env bash
# Test Port Discovery Integration
# Tests that dependent scripts correctly read and use ports from .ports file

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

TEST_DATA_DIR="${TEST_DATA_DIR:-/tmp/test_port_discovery_integration}"
TEST_PORTS_FILE="$TEST_DATA_DIR/.ports"

# Cleanup
cleanup() {
    rm -rf "$TEST_DATA_DIR" 2>/dev/null || true
}
trap cleanup EXIT

echo "========================================"
echo "Testing Port Discovery Integration"
echo "========================================"
echo

# Test 1: Verify .ports file can be sourced
test_ports_file_sourcing() {
    echo "Test 1: Verify .ports file can be sourced"
    echo "----------------------------------------"

    mkdir -p "$TEST_DATA_DIR"

    # Create a .ports file with alternate ports
    cat > "$TEST_PORTS_FILE" << 'EOF'
# Auto-generated by start_mssql_containers.sh
# Source this file to get the port assignments for this user's tutorial environment
MSSQL_DEV_PORT=14334
MSSQL_STG_PORT=14335
MSSQL_PRD_PORT=14336
EOF

    # Source the file
    source "$TEST_PORTS_FILE"

    # Verify variables are set
    if [[ "$MSSQL_DEV_PORT" != "14334" ]] || [[ "$MSSQL_STG_PORT" != "14335" ]] || [[ "$MSSQL_PRD_PORT" != "14336" ]]; then
        echo -e "${RED}✗ FAILED: Port variables not set correctly${NC}"
        echo "  DEV: $MSSQL_DEV_PORT (expected 14334)"
        echo "  STG: $MSSQL_STG_PORT (expected 14335)"
        echo "  PRD: $MSSQL_PRD_PORT (expected 14336)"
        return 1
    fi

    echo -e "${GREEN}✓ PASSED: .ports file can be sourced and variables set correctly${NC}"
    echo "  DEV: $MSSQL_DEV_PORT"
    echo "  STG: $MSSQL_STG_PORT"
    echo "  PRD: $MSSQL_PRD_PORT"
    echo
}

# Test 2: Test lb.sh port loading logic
test_lb_script_port_loading() {
    echo "Test 2: Test lb.sh port loading logic"
    echo "----------------------------------------"

    # Simulate lb.sh port loading logic
    PROJECT_DIR="$TEST_DATA_DIR"
    PORTS_FILE="$PROJECT_DIR/.ports"

    # Clear variables
    unset MSSQL_DEV_PORT MSSQL_STG_PORT MSSQL_PRD_PORT

    # Simulate lb.sh logic
    if [[ -f "$PORTS_FILE" ]]; then
        source "$PORTS_FILE"
    fi

    # Use ports from .ports file, or fall back to defaults
    MSSQL_DEV_PORT="${MSSQL_DEV_PORT:-14331}"
    MSSQL_STG_PORT="${MSSQL_STG_PORT:-14332}"
    MSSQL_PRD_PORT="${MSSQL_PRD_PORT:-14333}"

    # Verify ports were loaded (not defaults)
    if [[ "$MSSQL_DEV_PORT" == "14331" ]] || [[ "$MSSQL_STG_PORT" == "14332" ]] || [[ "$MSSQL_PRD_PORT" == "14333" ]]; then
        echo -e "${RED}✗ FAILED: Script is using default ports instead of .ports file${NC}"
        echo "  DEV: $MSSQL_DEV_PORT (expected 14334, not 14331)"
        echo "  STG: $MSSQL_STG_PORT (expected 14335, not 14332)"
        echo "  PRD: $MSSQL_PRD_PORT (expected 14336, not 14333)"
        return 1
    fi

    # Test port selection logic
    ENVIRONMENT="dev"
    case "$ENVIRONMENT" in
        dev) PORT="$MSSQL_DEV_PORT";;
        stg) PORT="$MSSQL_STG_PORT";;
        prd) PORT="$MSSQL_PRD_PORT";;
    esac

    if [[ "$PORT" != "14334" ]]; then
        echo -e "${RED}✗ FAILED: Port selection for dev environment incorrect${NC}"
        echo "  Got: $PORT (expected 14334)"
        return 1
    fi

    ENVIRONMENT="stg"
    case "$ENVIRONMENT" in
        dev) PORT="$MSSQL_DEV_PORT";;
        stg) PORT="$MSSQL_STG_PORT";;
        prd) PORT="$MSSQL_PRD_PORT";;
    esac

    if [[ "$PORT" != "14335" ]]; then
        echo -e "${RED}✗ FAILED: Port selection for stg environment incorrect${NC}"
        echo "  Got: $PORT (expected 14335)"
        return 1
    fi

    ENVIRONMENT="prd"
    case "$ENVIRONMENT" in
        dev) PORT="$MSSQL_DEV_PORT";;
        stg) PORT="$MSSQL_STG_PORT";;
        prd) PORT="$MSSQL_PRD_PORT";;
    esac

    if [[ "$PORT" != "14336" ]]; then
        echo -e "${RED}✗ FAILED: Port selection for prd environment incorrect${NC}"
        echo "  Got: $PORT (expected 14336)"
        return 1
    fi

    echo -e "${GREEN}✓ PASSED: lb.sh port loading logic works correctly${NC}"
    echo "  All environments select correct ports from .ports file"
    echo
}

# Test 3: Test setup_liquibase_environment.sh port loading
test_setup_script_port_loading() {
    echo "Test 3: Test setup_liquibase_environment.sh port loading"
    echo "----------------------------------------"

    # Simulate setup_liquibase_environment.sh port loading logic
    LIQUIBASE_TUTORIAL_DATA_DIR="$TEST_DATA_DIR"
    PORTS_FILE="$LIQUIBASE_TUTORIAL_DATA_DIR/.ports"

    # Clear variables
    unset MSSQL_DEV_PORT MSSQL_STG_PORT MSSQL_PRD_PORT

    # Simulate setup script logic
    if [[ -f "$PORTS_FILE" ]]; then
        source "$PORTS_FILE"
    fi

    # Use ports from .ports file, or fall back to defaults
    MSSQL_DEV_PORT="${MSSQL_DEV_PORT:-14331}"
    MSSQL_STG_PORT="${MSSQL_STG_PORT:-14332}"
    MSSQL_PRD_PORT="${MSSQL_PRD_PORT:-14333}"

    # Verify ports were loaded
    if [[ "$MSSQL_DEV_PORT" == "14331" ]] || [[ "$MSSQL_STG_PORT" == "14332" ]] || [[ "$MSSQL_PRD_PORT" == "14333" ]]; then
        echo -e "${RED}✗ FAILED: setup script is using default ports${NC}"
        return 1
    fi

    # Test that ports would be used correctly in properties file creation
    for env in dev stg prd; do
        case "$env" in
            dev) port="$MSSQL_DEV_PORT";;
            stg) port="$MSSQL_STG_PORT";;
            prd) port="$MSSQL_PRD_PORT";;
        esac

        # Verify port is correct for each environment
        case "$env" in
            dev) expected=14334;;
            stg) expected=14335;;
            prd) expected=14336;;
        esac

        if [[ "$port" != "$expected" ]]; then
            echo -e "${RED}✗ FAILED: Port for $env environment incorrect${NC}"
            echo "  Got: $port (expected $expected)"
            return 1
        fi
    done

    echo -e "${GREEN}✓ PASSED: setup_liquibase_environment.sh port loading works correctly${NC}"
    echo "  Ports correctly loaded for properties file creation"
    echo
}

# Test 4: Test fallback behavior when .ports file doesn't exist
test_fallback_to_defaults() {
    echo "Test 4: Test fallback behavior (no .ports file)"
    echo "----------------------------------------"

    # Remove .ports file
    rm -f "$TEST_PORTS_FILE"

    # Clear variables
    unset MSSQL_DEV_PORT MSSQL_STG_PORT MSSQL_PRD_PORT

    # Simulate script logic without .ports file
    PORTS_FILE="$TEST_DATA_DIR/.ports"
    if [[ -f "$PORTS_FILE" ]]; then
        source "$PORTS_FILE"
    fi

    # Use ports from .ports file, or fall back to defaults
    MSSQL_DEV_PORT="${MSSQL_DEV_PORT:-14331}"
    MSSQL_STG_PORT="${MSSQL_STG_PORT:-14332}"
    MSSQL_PRD_PORT="${MSSQL_PRD_PORT:-14333}"

    # Verify defaults are used
    if [[ "$MSSQL_DEV_PORT" != "14331" ]] || [[ "$MSSQL_STG_PORT" != "14332" ]] || [[ "$MSSQL_PRD_PORT" != "14333" ]]; then
        echo -e "${RED}✗ FAILED: Fallback to defaults not working${NC}"
        echo "  DEV: $MSSQL_DEV_PORT (expected 14331)"
        echo "  STG: $MSSQL_STG_PORT (expected 14332)"
        echo "  PRD: $MSSQL_PRD_PORT (expected 14333)"
        return 1
    fi

    echo -e "${GREEN}✓ PASSED: Fallback to defaults works correctly${NC}"
    echo "  When .ports file doesn't exist, defaults (14331-14333) are used"
    echo
}

# Main
main() {
    test_ports_file_sourcing || exit 1
    test_lb_script_port_loading || exit 1
    test_setup_script_port_loading || exit 1
    test_fallback_to_defaults || exit 1

    echo "========================================"
    echo -e "${GREEN}All Integration Tests Passed!${NC}"
    echo "========================================"
    echo
    echo "Summary:"
    echo "  ✓ .ports file can be sourced correctly"
    echo "  ✓ lb.sh port loading logic works"
    echo "  ✓ setup_liquibase_environment.sh port loading works"
    echo "  ✓ Fallback to defaults works when .ports file missing"
}

main "$@"
